# Schema for configuration files of the Paywall module.

field.formatter.settings.paywall_formatter:
  type: mapping
  label: 'Paywall field display format settings'
  mapping:
    message:
      type: string
      label: 'Paywall message'
    hidden_fields:
      type: sequence
      label: 'Hidden fields'
      sequence:
      ￼type: field_paywall_hidden_fields.[%key] 

field_paywall_hidden_fields.single:*:
  type: string
  label: Hidden field name